name: CICD for Serverless Application
run-name: ${{ github.actor }} is doing CICD for serverless application

on:
  push:
    branches: [ main, "*" ]

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by a ${{ github.event_name }} event."

  install-dependencies:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v3
          - name: Run installation of dependencies commands
            run: npm install
           
  unit-testing:
        runs-on: ubuntu-latest
        steps:
           - name: Check out repository code
             uses: actions/checkout@v3
           - name: Run installation of dependencies commands
             run: npm install
           - name: Run unit testing command
             run: npm test      
 
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
       node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
       args: deploy
      env:
       AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

name: Deploy and Monitor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Additional steps for your deployment process

  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  # Change this to your desired region

      - name: Send Custom Metric to CloudWatch
        run: |
          aws cloudwatch put-metric-data \
            --namespace "CustomNamespace" \
            --metric-name "CustomMetric" \
            --value 1 \
            --unit Count

      # Additional monitoring steps as needed




